import de.monticore.grammar.grammar._ast.*;
import de.monticore.grammar.grammar_withconcepts.Grammar_WithConceptsMill;
import de.monticore.grammar.grammar_withconcepts._parser.Grammar_WithConceptsParser;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Optional;

/**
 * Generates a PlantUML class diagram from MontiCore grammar files.
 * This helps visualize the AST structure generated from the grammar.
 */
public class ASTClassDiagramGenerator {

    public static void main(String[] args) {
        // Default grammar to visualize - can be changed
        String grammarPath = "src/main/grammars/BehaviorTree.mc4";
        String outputDir = "target/diagrams";
        
        if (args.length > 0) {
            grammarPath = args[0];
        }
        
        System.out.println("=== AST Class Diagram Generator ===");
        System.out.println("Grammar: " + grammarPath);
        
        try {
            generateDiagram(grammarPath, outputDir);
        } catch (Exception e) {
            System.err.println("Error generating diagram: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    public static void generateDiagram(String grammarPath, String outputDir) throws IOException {
        // Create output directory
        Files.createDirectories(Paths.get(outputDir));
        
        // Initialize MontiCore
        Grammar_WithConceptsMill.init();
        
        // Parse the grammar
        Grammar_WithConceptsParser parser = new Grammar_WithConceptsParser();
        Optional<ASTMCGrammar> grammarOpt = parser.parse(grammarPath);
        
        if (grammarOpt.isEmpty()) {
            System.err.println("Failed to parse grammar: " + grammarPath);
            return;
        }
        
        ASTMCGrammar grammar = grammarOpt.get();
        String grammarName = grammar.getName();
        
        System.out.println("Parsed grammar: " + grammarName);
        System.out.println("Productions found: " + grammar.getClassProdList().size());
        
        // Generate PlantUML manually from grammar structure
        StringBuilder plantUml = new StringBuilder();
        plantUml.append("@startuml ").append(grammarName).append("_AST\n\n");
        plantUml.append("' Auto-generated AST Class Diagram for ").append(grammarName).append("\n");
        plantUml.append("' Generated by ASTClassDiagramGenerator\n\n");
        plantUml.append("skinparam classAttributeIconSize 0\n");
        plantUml.append("skinparam classFontSize 12\n");
        plantUml.append("hide empty members\n\n");
        
        // Add title
        plantUml.append("title AST Classes for ").append(grammarName).append(" Grammar\n\n");
        
        // Process interface productions
        grammar.getInterfaceProdList().forEach(prod -> {
            plantUml.append("interface AST").append(prod.getName()).append(" {\n");
            plantUml.append("}\n\n");
        });
        
        // Process abstract productions
        grammar.getAbstractProdList().forEach(prod -> {
            plantUml.append("abstract class AST").append(prod.getName()).append(" {\n");
            plantUml.append("}\n\n");
        });
        
        // Process class productions (the main rules)
        grammar.getClassProdList().forEach(prod -> {
            String className = "AST" + prod.getName();
            plantUml.append("class ").append(className).append(" {\n");
            
            // Add attributes from the production's alternatives
            prod.getAltList().forEach(alt -> {
                alt.getComponentList().forEach(comp -> {
                    String attrInfo = extractAttributeInfo(comp);
                    if (attrInfo != null) {
                        plantUml.append("  ").append(attrInfo).append("\n");
                    }
                });
            });
            
            plantUml.append("}\n\n");
            
            // Add inheritance relationships
            prod.getSuperRuleList().forEach(superRule -> {
                plantUml.append(className).append(" --|> AST").append(superRule.getName()).append("\n");
            });
            
            prod.getSuperInterfaceRuleList().forEach(superInterface -> {
                plantUml.append(className).append(" ..|> AST").append(superInterface.getName()).append("\n");
            });
        });
        
        // Process enum productions
        grammar.getEnumProdList().forEach(prod -> {
            plantUml.append("enum AST").append(prod.getName()).append(" {\n");
            prod.getConstantList().forEach(constant -> {
                plantUml.append("  ").append(constant.getName()).append("\n");
            });
            plantUml.append("}\n\n");
        });
        
        plantUml.append("@enduml\n");
        
        // Write PlantUML file
        String outputFile = outputDir + "/" + grammarName + "_AST.puml";
        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile))) {
            writer.print(plantUml.toString());
        }
        
        System.out.println("\n✓ PlantUML diagram saved to: " + outputFile);
        System.out.println("\nTo view the diagram:");
        System.out.println("  1. Open " + outputFile + " in VS Code with PlantUML extension");
        System.out.println("  2. Or paste content at https://www.plantuml.com/plantuml/uml/");
        System.out.println("  3. Or use: java -jar plantuml.jar " + outputFile);
        
        // Also print a summary
        printGrammarSummary(grammar);
    }
    
    private static String extractAttributeInfo(ASTRuleComponent comp) {
        // Handle different types of rule components
        if (comp instanceof ASTNonTerminal) {
            ASTNonTerminal nt = (ASTNonTerminal) comp;
            String name = nt.isPresentUsageName() ? nt.getUsageName() : nt.getName().toLowerCase();
            String type = "AST" + nt.getName();
            if (nt.getIteration() == ASTConstantsGrammar.STAR || nt.getIteration() == ASTConstantsGrammar.PLUS) {
                return "+" + name + " : List<" + type + ">";
            }
            return "+" + name + " : " + type;
        } else if (comp instanceof ASTTerminal) {
            ASTTerminal t = (ASTTerminal) comp;
            if (t.isPresentUsageName()) {
                return "+" + t.getUsageName() + " : String";
            }
        } else if (comp instanceof ASTConstantGroup) {
            ASTConstantGroup cg = (ASTConstantGroup) comp;
            if (cg.isPresentUsageName()) {
                return "+" + cg.getUsageName() + " : boolean";
            }
        }
        return null;
    }
    
    private static void printGrammarSummary(ASTMCGrammar grammar) {
        System.out.println("\n=== Grammar Summary ===");
        System.out.println("Grammar Name: " + grammar.getName());
        
        System.out.println("\nProductions:");
        System.out.println("  Interface Productions: " + grammar.getInterfaceProdList().size());
        grammar.getInterfaceProdList().forEach(p -> System.out.println("    - " + p.getName()));
        
        System.out.println("  Abstract Productions: " + grammar.getAbstractProdList().size());
        grammar.getAbstractProdList().forEach(p -> System.out.println("    - " + p.getName()));
        
        System.out.println("  Class Productions: " + grammar.getClassProdList().size());
        grammar.getClassProdList().forEach(p -> System.out.println("    - " + p.getName()));
        
        System.out.println("  Enum Productions: " + grammar.getEnumProdList().size());
        grammar.getEnumProdList().forEach(p -> System.out.println("    - " + p.getName()));
        
        System.out.println("  External Productions: " + grammar.getExternalProdList().size());
        System.out.println("  Lexer Productions: " + grammar.getLexProdList().size());
    }
}
