
using ModelLoader;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;




/// <summary>
/// This class is responsible for initializing the system by registering entity types, action types, and predicate types.
/// It also creates initial entities and adds them to the blackboard.
/// </summary>
public class BlackboardWriter
{
    private Blackboard<FastName> blackboard;
    private FactoryParameter entityFactory;
    private FactoryAction actionFactory;
    private readonly FactoryPredicate predicateFactory;

    public BlackboardWriter(Blackboard<FastName> blackboard)
    {
        this.blackboard = blackboard;
        this.entityFactory = FactoryParameter.Instance;
        this.actionFactory = FactoryAction.Instance;
        this.predicateFactory = FactoryPredicate.Instance;
    }
/// <summary>
/// Registers all input parameter instances from the parameter_instances.txt file into the blackboard
/// </summary>
/// <returns></returns>
        public List<Entity> registerInputParameterInstances()
    {
        List<Entity> inputInstances = new List<Entity>();
        
        // Read parameter instances from the file generated by MontiCore
        string parameterInstancesFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "Blackboard", "parameter_instances.txt");
        
        if (File.Exists(parameterInstancesFile))
        {
            Console.WriteLine($"Reading parameter instances from: {parameterInstancesFile}");
            
            string[] lines = File.ReadAllLines(parameterInstancesFile);
            
            foreach (string line in lines)
            {
                // Skip comments and empty lines
                if (string.IsNullOrWhiteSpace(line) || line.StartsWith("#"))
                    continue;
                
                // Parse the line: type,name
                string[] parts = line.Split(',');
                if (parts.Length == 2)
                {
                    string parameterType = parts[0].Trim();
                    string instanceName = parts[1].Trim();
                    
                    Console.WriteLine($"Creating {parameterType} instance: {instanceName}");
                    
                    // Create the parameter instance
                    var instance = entityFactory.CreateParameter(parameterType, instanceName);
                    inputInstances.Add(instance);
                    blackboard.RegisterEntityIfNotExists(instance);
                }
            }
            
            Console.WriteLine($"Created {inputInstances.Count} parameter instances");
        }
        else
        {
            Console.WriteLine($"Warning: Parameter instances file not found at {parameterInstancesFile}");
            Console.WriteLine("Please run 'gradle extractParameterInstances' in the MontiCoreTool directory first");
        }

        return inputInstances;
    }

    /// <summary>
    /// Registers all parameter types from the ParameterTypes folder into the blackboard
    /// </summary>
    public void RegisterParameterTypes()
    {
        Console.WriteLine("Registering parameter types...");
        
        try
        {
            // Get the path to the ParameterTypes folder
            string parameterTypesPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "ModelLoader", "ParameterTypes");
            
            if (Directory.Exists(parameterTypesPath))
            {
                // Get all .cs files in the ParameterTypes folder
                string[] csFiles = Directory.GetFiles(parameterTypesPath, "*.cs");
                
                foreach (string file in csFiles)
                {
                    string fileName = Path.GetFileNameWithoutExtension(file);
                    Console.WriteLine($"Processing parameter type: {fileName}");
                    
                    try
                    {
                        // Register the entity type
                        blackboard.RegisterEntityType(new FastName(fileName));
                        Console.WriteLine($"Registered entity type: {fileName}");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error processing parameter type {fileName}: {ex.Message}");
                    }
                }
                
                Console.WriteLine("Parameter types registration completed");
            }
            else
            {
                Console.WriteLine($"Warning: ParameterTypes folder not found at {parameterTypesPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error registering parameter types: {ex.Message}");
        }
    }

    /// <summary>
    /// Registers all predicate types from the PredicateTypes folder into the blackboard
    /// </summary>
    public void RegisterPredicateTypes()
    {
        Console.WriteLine("Registering predicate types...");
        
        try
        {
            // Get the path to the PredicateTypes folder
            string predicateTypesPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "ModelLoader", "PredicateTypes");
            
            if (Directory.Exists(predicateTypesPath))
            {
                // Get all .cs files in the PredicateTypes folder
                string[] csFiles = Directory.GetFiles(predicateTypesPath, "*.cs");
                
                foreach (string file in csFiles)
                {
                    string fileName = Path.GetFileNameWithoutExtension(file);
                    Console.WriteLine($"Processing predicate type: {fileName}");
                    
                    try
                    {
                        // Register the predicate type
                        blackboard.RegisterPredicateType(new FastName(fileName));
                        Console.WriteLine($"Registered predicate type: {fileName}");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error processing predicate type {fileName}: {ex.Message}");
                    }
                }
                
                Console.WriteLine("Predicate types registration completed");
            }
            else
            {
                Console.WriteLine($"Warning: PredicateTypes folder not found at {predicateTypesPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error registering predicate types: {ex.Message}");
        }
    }

    /// <summary>
    /// Registers all action types from the ActionTypes folder into the blackboard
    /// </summary>
    public void RegisterActionTypes()
    {
        Console.WriteLine("Registering action types...");
        
        try
        {
            // Get the path to the ActionTypes folder
            string actionTypesPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "ModelLoader", "ActionTypes");
            
            if (Directory.Exists(actionTypesPath))
            {
                // Get all .cs files in the ActionTypes folder
                string[] csFiles = Directory.GetFiles(actionTypesPath, "*.cs");
                
                foreach (string file in csFiles)
                {
                    string fileName = Path.GetFileNameWithoutExtension(file);
                    Console.WriteLine($"Processing action type: {fileName}");
                    
                    try
                    {
                        // Register the action type
                        blackboard.RegisterActionType(new FastName(fileName));
                        Console.WriteLine($"Registered action type: {fileName}");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error processing action type {fileName}: {ex.Message}");
                    }
                }
                
                Console.WriteLine("Action types registration completed");
            }
            else
            {
                Console.WriteLine($"Warning: ActionTypes folder not found at {actionTypesPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error registering action types: {ex.Message}");
        }
    }

    /// <summary>
    /// Registers all types (parameter, predicate, and action types) into the blackboard
    /// </summary>
    public void RegisterAllTypes()
    {
        Console.WriteLine("Starting registration of all types...");
        
        RegisterParameterTypes();
        RegisterPredicateTypes();
        RegisterActionTypes();
        
        Console.WriteLine("All types registration completed");
    }

    /// <summary>
    /// Takes a single parameter instance, determines its base type, and registers it in the appropriate blackboard dictionary
    /// </summary>
    /// <param name="parameterInstance">The parameter instance to register</param>
    public void RegisterParameterInstanceByBaseType(Entity parameterInstance)
    {
        try
        {
            // Get the base type from the entity
            string baseTypeName = GetBaseTypeName(parameterInstance);
            
            Console.WriteLine($"Registering {parameterInstance.GetType().Name} instance '{parameterInstance.ID}' as base type '{baseTypeName}'");
            
            // Register the instance in the appropriate blackboard dictionary based on base type
            switch (baseTypeName.ToLower())
            {
                case "element":
                    blackboard.RegisterEntityIfNotExists(parameterInstance);
                    Console.WriteLine($"  ✅ Registered as Element: {parameterInstance.ID}");
                    break;
                    
                case "agent":
                    blackboard.RegisterEntityIfNotExists(parameterInstance);
                    Console.WriteLine($"  ✅ Registered as Agent: {parameterInstance.ID}");
                    break;
                    
                case "location":
                    blackboard.RegisterEntityIfNotExists(parameterInstance);
                    Console.WriteLine($"  ✅ Registered as Location: {parameterInstance.ID}");
                    break;
                    
                case "tool":
                    blackboard.RegisterEntityIfNotExists(parameterInstance);
                    Console.WriteLine($"  ✅ Registered as Tool: {parameterInstance.ID}");
                    break;
                    
                case "layer":
                    blackboard.RegisterEntityIfNotExists(parameterInstance);
                    Console.WriteLine($"  ✅ Registered as Layer: {parameterInstance.ID}");
                    break;
                    
                case "module":
                    blackboard.RegisterEntityIfNotExists(parameterInstance);
                    Console.WriteLine($"  ✅ Registered as Module: {parameterInstance.ID}");
                    break;
                    
                default:
                    Console.WriteLine($"  ⚠️ Unknown base type '{baseTypeName}' for instance '{parameterInstance.ID}', registering as generic Entity");
                    blackboard.RegisterEntityIfNotExists(parameterInstance);
                    break;
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  ❌ Error registering instance '{parameterInstance.ID}': {ex.Message}");
        }
    }

    /// <summary>
    /// Determines the base type name of an entity instance
    /// </summary>
    /// <param name="instance">The entity instance</param>
    /// <returns>The base type name (e.g., "Element", "Agent", "Location")</returns>
    private string GetBaseTypeName(Entity instance)
    {
        // Get the base type from the entity's BaseType property
        if (instance.BaseType != null)
        {
            return instance.BaseType.ToString();
        }
        
        // Fallback: determine base type from inheritance hierarchy
        Type currentType = instance.GetType();
        
        // Check inheritance hierarchy to find the base type
        while (currentType != null && currentType != typeof(Entity))
        {
            if (currentType == typeof(Element))
                return "Element";
            if (currentType == typeof(Agent))
                return "Agent";
            if (currentType == typeof(Location))
                return "Location";
            if (currentType == typeof(Tool))
                return "Tool";
            if (currentType == typeof(Layer))
                return "Layer";
            if (currentType == typeof(Module))
                return "Module";
                
            currentType = currentType.BaseType;
        }
        
        // If no specific base type found, return the actual type name
        return instance.GetType().Name;
    }

    /// <summary>
    /// Takes a single predicate instance and registers it in the appropriate blackboard dictionary
    /// </summary>
    /// <param name="predicateInstance">The predicate instance to register</param>
    public void RegisterPredicateInstanceByType(Predicate predicateInstance)
    {
        try
        {
            // Get the predicate type name and instance name
            string predicateTypeName = predicateInstance.GetType().Name;
            string instanceName = predicateInstance.PredicateName.ToString();
            
            Console.WriteLine($"Registering {predicateTypeName} instance '{instanceName}'");
            
            // Create a key for the predicate (using instance name)
            
            
            // Register the predicate in the blackboard
            // Predicates are stored in PredicateValues dictionary as HashSet<Predicate>
            blackboard.SetPredicate(predicateInstance.PredicateName, predicateInstance);
            
            Console.WriteLine($"  ✅ Registered {predicateTypeName} predicate with key '{instanceName}'");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"  ❌ Error registering predicate '{predicateInstance.GetType().Name}': {ex.Message}");
        }
    }

    /// <summary>
    /// Parses a MontiCore grammar text file and generates parameter instances
    /// Expected format: ParameterInstance: typeName {instanceName}
    /// </summary>
    /// <param name="filePath">Path to the MontiCore grammar text file</param>
    /// <returns>List of created parameter instances</returns>
    public List<Entity> ParseMontiCoreGrammarFile(string filePath)
    {
        List<Entity> createdInstances = new List<Entity>();
        
        try
        {
            Console.WriteLine($"Parsing MontiCore grammar file: {filePath}");
            
            if (!File.Exists(filePath))
            {
                Console.WriteLine($"❌ Error: File not found at {filePath}");
                return createdInstances;
            }
            
            string[] lines = File.ReadAllLines(filePath);
            int lineNumber = 0;
            int successCount = 0;
            int errorCount = 0;
            
            foreach (string line in lines)
            {
                lineNumber++;
                
                // Skip empty lines and comments
                if (string.IsNullOrWhiteSpace(line) || line.Trim().StartsWith("#"))
                {
                    continue;
                }
                
                try
                {
                    // Parse the line: ParameterInstance: typeName {instanceName}
                    var instance = ParseParameterInstanceLine(line.Trim());
                    
                    if (instance != null)
                    {
                        createdInstances.Add(instance);
                        successCount++;
                        Console.WriteLine($"  ✅ Line {lineNumber}: Created {instance.GetType().Name} instance '{instance.ID}'");
                    }
                }
                catch (Exception ex)
                {
                    errorCount++;
                    Console.WriteLine($"  ❌ Line {lineNumber}: Error parsing '{line.Trim()}': {ex.Message}");
                }
            }
            
            Console.WriteLine($"\n📊 Parsing Summary:");
            Console.WriteLine($"  ✅ Successfully created: {successCount} instances");
            Console.WriteLine($"  ❌ Errors: {errorCount}");
            Console.WriteLine($"  📄 Total lines processed: {lineNumber}");
            
        }
        catch (Exception ex)
        {
            Console.WriteLine($"❌ Error reading file {filePath}: {ex.Message}");
        }
        
        return createdInstances;
    }
    
    /// <summary>
    /// Parses a single line in MontiCore grammar format
    /// Expected format: ParameterInstance: typeName {instanceName}
    /// </summary>
    /// <param name="line">The line to parse</param>
    /// <returns>Created Entity instance or null if parsing failed</returns>
    private Entity ParseParameterInstanceLine(string line)
    {
        // Expected format: ParameterInstance: typeName {instanceName}
        const string prefix = "ParameterInstance:";
        
        if (!line.StartsWith(prefix))
        {
            throw new ArgumentException($"Line does not start with '{prefix}'");
        }
        
        // Remove the prefix and trim
        string content = line.Substring(prefix.Length).Trim();
        
        // Find the opening and closing braces
        int openBraceIndex = content.IndexOf('{');
        int closeBraceIndex = content.LastIndexOf('}');
        
        if (openBraceIndex == -1 || closeBraceIndex == -1 || openBraceIndex >= closeBraceIndex)
        {
            throw new ArgumentException("Invalid brace format. Expected: typeName {instanceName}");
        }
        
        // Extract type name and instance name
        string typeName = content.Substring(0, openBraceIndex).Trim();
        string instanceName = content.Substring(openBraceIndex + 1, closeBraceIndex - openBraceIndex - 1).Trim();
        
        if (string.IsNullOrWhiteSpace(typeName))
        {
            throw new ArgumentException("Type name cannot be empty");
        }
        
        if (string.IsNullOrWhiteSpace(instanceName))
        {
            throw new ArgumentException("Instance name cannot be empty");
        }
        
        // Create the parameter instance using the factory
        return entityFactory.CreateParameter(typeName, instanceName);
    }
    
    /// <summary>
    /// Parses a MontiCore grammar text file and registers all parameter instances in the blackboard
    /// </summary>
    /// <param name="filePath">Path to the MontiCore grammar text file</param>
    public void ParseAndRegisterMontiCoreGrammarFile(string filePath)
    {
        Console.WriteLine($"\n=== PARSING AND REGISTERING MONTICORE GRAMMAR FILE ===");
        
        var instances = ParseMontiCoreGrammarFile(filePath);
        
        Console.WriteLine($"\n=== REGISTERING {instances.Count} INSTANCES IN BLACKBOARD ===");
        
        int registeredCount = 0;
        int skippedCount = 0;
        
        foreach (var instance in instances)
        {
            try
            {
                // Register the instance by its base type
                RegisterParameterInstanceByBaseType(instance);
                registeredCount++;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"  ❌ Error registering instance '{instance.ID}': {ex.Message}");
                skippedCount++;
            }
        }
        
        Console.WriteLine($"\n📊 Registration Summary:");
        Console.WriteLine($"  ✅ Successfully registered: {registeredCount} instances");
        Console.WriteLine($"  ⚠️ Skipped: {skippedCount} instances");
    }


}