
using ModelLoader;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;




/// <summary>
/// This class is responsible for initializing the system by registering entity types, action types, and predicate types.
/// It also creates initial entities and adds them to the blackboard.
/// </summary>
public class BlackboardWriter
{
    private Blackboard<FastName> blackboard;
    private FactoryParameter entityFactory;
    private FactoryAction actionFactory;
    private readonly FactoryPredicate predicateFactory;

    public BlackboardWriter(Blackboard<FastName> blackboard)
    {
        this.blackboard = blackboard;
        this.entityFactory = FactoryParameter.Instance;
        this.actionFactory = FactoryAction.Instance;
        this.predicateFactory = FactoryPredicate.Instance;
    }

        public List<Entity> registerInputParameterInstances()
    {
        List<Entity> inputInstances = new List<Entity>();
        
        // Read parameter instances from the file generated by MontiCore
        string parameterInstancesFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "Blackboard", "parameter_instances.txt");
        
        if (File.Exists(parameterInstancesFile))
        {
            Console.WriteLine($"Reading parameter instances from: {parameterInstancesFile}");
            
            string[] lines = File.ReadAllLines(parameterInstancesFile);
            
            foreach (string line in lines)
            {
                // Skip comments and empty lines
                if (string.IsNullOrWhiteSpace(line) || line.StartsWith("#"))
                    continue;
                
                // Parse the line: type,name
                string[] parts = line.Split(',');
                if (parts.Length == 2)
                {
                    string parameterType = parts[0].Trim();
                    string instanceName = parts[1].Trim();
                    
                    Console.WriteLine($"Creating {parameterType} instance: {instanceName}");
                    
                    // Create the parameter instance
                    var instance = entityFactory.CreateParameter(parameterType, instanceName);
                    inputInstances.Add(instance);
                    blackboard.RegisterEntityIfNotExists(instance);
                }
            }
            
            Console.WriteLine($"Created {inputInstances.Count} parameter instances");
        }
        else
        {
            Console.WriteLine($"Warning: Parameter instances file not found at {parameterInstancesFile}");
            Console.WriteLine("Please run 'gradle extractParameterInstances' in the MontiCoreTool directory first");
        }

        return inputInstances;
    }

    /// <summary>
    /// Registers all parameter types from the ParameterTypes folder into the blackboard
    /// </summary>
    public void RegisterParameterTypes()
    {
        Console.WriteLine("Registering parameter types...");
        
        try
        {
            // Get the path to the ParameterTypes folder
            string parameterTypesPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "ModelLoader", "ParameterTypes");
            
            if (Directory.Exists(parameterTypesPath))
            {
                // Get all .cs files in the ParameterTypes folder
                string[] csFiles = Directory.GetFiles(parameterTypesPath, "*.cs");
                
                foreach (string file in csFiles)
                {
                    string fileName = Path.GetFileNameWithoutExtension(file);
                    Console.WriteLine($"Processing parameter type: {fileName}");
                    
                    try
                    {
                        // Load the type using reflection
                        Type parameterType = Type.GetType($"ModelLoader.ParameterTypes.{fileName}, BehaviorTreeMainProject");
                        
                        if (parameterType != null && typeof(Entity).IsAssignableFrom(parameterType))
                        {
                            // Register the type in the blackboard
                            blackboard.SetEntityType(new FastName(fileName), parameterType);
                            Console.WriteLine($"Registered parameter type: {fileName}");
                        }
                        else
                        {
                            Console.WriteLine($"Warning: Could not load or validate type {fileName}");
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error processing parameter type {fileName}: {ex.Message}");
                    }
                }
                
                Console.WriteLine("Parameter types registration completed");
            }
            else
            {
                Console.WriteLine($"Warning: ParameterTypes folder not found at {parameterTypesPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error registering parameter types: {ex.Message}");
        }
    }

    /// <summary>
    /// Registers all predicate types from the PredicateTypes folder into the blackboard
    /// </summary>
    public void RegisterPredicateTypes()
    {
        Console.WriteLine("Registering predicate types...");
        
        try
        {
            // Get the path to the PredicateTypes folder
            string predicateTypesPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "ModelLoader", "PredicateTypes");
            
            if (Directory.Exists(predicateTypesPath))
            {
                // Get all .cs files in the PredicateTypes folder
                string[] csFiles = Directory.GetFiles(predicateTypesPath, "*.cs");
                
                foreach (string file in csFiles)
                {
                    string fileName = Path.GetFileNameWithoutExtension(file);
                    Console.WriteLine($"Processing predicate type: {fileName}");
                    
                    try
                    {
                        // Load the type using reflection
                        Type predicateType = Type.GetType($"ModelLoader.PredicateTypes.{fileName}, BehaviorTreeMainProject");
                        
                        if (predicateType != null && typeof(Predicate).IsAssignableFrom(predicateType))
                        {
                            // Register the type in the blackboard
                            blackboard.SetPredicateType(new FastName(fileName), predicateType);
                            Console.WriteLine($"Registered predicate type: {fileName}");
                        }
                        else
                        {
                            Console.WriteLine($"Warning: Could not load or validate type {fileName}");
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error processing predicate type {fileName}: {ex.Message}");
                    }
                }
                
                Console.WriteLine("Predicate types registration completed");
            }
            else
            {
                Console.WriteLine($"Warning: PredicateTypes folder not found at {predicateTypesPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error registering predicate types: {ex.Message}");
        }
    }

    /// <summary>
    /// Registers all action types from the ActionTypes folder into the blackboard
    /// </summary>
    public void RegisterActionTypes()
    {
        Console.WriteLine("Registering action types...");
        
        try
        {
            // Get the path to the ActionTypes folder
            string actionTypesPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src", "ModelLoader", "ActionTypes");
            
            if (Directory.Exists(actionTypesPath))
            {
                // Get all .cs files in the ActionTypes folder
                string[] csFiles = Directory.GetFiles(actionTypesPath, "*.cs");
                
                foreach (string file in csFiles)
                {
                    string fileName = Path.GetFileNameWithoutExtension(file);
                    Console.WriteLine($"Processing action type: {fileName}");
                    
                    try
                    {
                        // Load the type using reflection
                        Type actionType = Type.GetType($"ModelLoader.ActionTypes.{fileName}, BehaviorTreeMainProject");
                        
                        if (actionType != null && typeof(Action).IsAssignableFrom(actionType))
                        {
                            // Register the type in the blackboard
                            blackboard.SetActionType(new FastName(fileName), actionType);
                            Console.WriteLine($"Registered action type: {fileName}");
                        }
                        else
                        {
                            Console.WriteLine($"Warning: Could not load or validate type {fileName}");
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error processing action type {fileName}: {ex.Message}");
                    }
                }
                
                Console.WriteLine("Action types registration completed");
            }
            else
            {
                Console.WriteLine($"Warning: ActionTypes folder not found at {actionTypesPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error registering action types: {ex.Message}");
        }
    }

    /// <summary>
    /// Registers all types (parameter, predicate, and action types) into the blackboard
    /// </summary>
    public void RegisterAllTypes()
    {
        Console.WriteLine("Starting registration of all types...");
        
        RegisterParameterTypes();
        RegisterPredicateTypes();
        RegisterActionTypes();
        
        Console.WriteLine("All types registration completed");
    }
    

}